<?php

function koldkaergaard_menu() {

  $items['admin/config/koldkaergaard'] = array(
    'title' => 'Koldkaergaard',
    'position' => 'left',
    'weight' => -50,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access content'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );

  $items['admin/config/koldkaergaard/moderator'] = array(
    'title' => 'Koldkaergaard',
    'page callback' => 'drupal_goto',
    'page arguments' => array('admin/koldkaergaard/moderator'),
    'access arguments' => array('access content'),
  );

  $items['admin/koldkaergaard/moderator'] = array(
    'title' => 'Koldkaergaard',
    'page callback' => '_koldkaergaard_moderator_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

function _koldkaergaard_moderator_page(){

  $items['koldkaergaard'] = array(
    '#type' => 'fieldset',
    '#collapsible' => true,
    '#collapsed' => true,
    '#title' => t('Koldkaergaard'),
  );

  $items['koldkaergaard']['submissions'] = array(
    '#theme' => 'link',
    '#text' => 'View booking form submissions',
    '#path' => 'admin/structure/entityform_types/manage/online_booking/submissions',
    '#options' => array('attributes' => array('title' => 'View booking form submissions'), 'html' => false),
    '#description' => t('Allows you to manage online booking form submissions'),
    '#prefix' => '<p>',
    '#sufix' => '</p>',
  );

  return $items;
}